// This Java program was generated by ChatGPT

public class J1_quicksort {

    public J1_quicksort() { }

    public static void quickSort(int[] arr, int left, int right) {
        if (left < right) {
            int pivotIndex = J1_quicksort.partition(arr, left, right);
            J1_quicksort.quickSort(arr, left, pivotIndex - 1);
            J1_quicksort.quickSort(arr, pivotIndex + 1, right);
        }
    }

    protected static int partition(int[] arr, int left, int right) {
        int pivot = arr[right];
        int i = left - 1;
        for (int j = left; j < right; j = j + 1) {
            if (arr[j] <= pivot) {
                i = i + 1;
                J1_quicksort.swap(arr, i, j);
            }
        }
        J1_quicksort.swap(arr, i + 1, right);
        return i + 1;
    }

    protected static void swap(int[] arr, int i, int j) {
        int temp = arr[i];
        arr[i] = arr[j];
        arr[j] = temp;
    }

    public static int test() {
        int[] a = new int[7];
        a[0] = 64; a[1] = 34; a[2] = 25; a[3] = 12; a[4] = 22; a[5] = 11; a[6] = 100;
        J1_quicksort.quickSort(a, 0, a.length - 1);
        return a[6] + a[1] + a[0];
    }

}
