// Generated by libfuzzer
// ./crash-6a7e004703856fc2546d4c9de3682a1bbe834cb2
public class static_arr {
	public static int[] t = new int[100];
	public Foo() {
	}
	public static int test() {
		return (Foo.m0());
	}
	public static int m0() {
		return (Foo.t[0]);
	}
	public static int m1() {
		return 1;
	}
	public static int m2() {
		return 1;
	}
	public static int m3() {
		return 1;
	}

	public static_arr() {}
}
