// Generated by libfuzzer
// ./crash-6a7e004703856fc2546d4c9de3682a1bbe834cb2
public class static_arr2 {
	public static int[] t = new int[100];
	public static_arr2() {
	}
	public static int test() {
        static_arr2.t[0] = 123;
		return (static_arr2.m0());
	}
	public static int m0() {
		return (static_arr2.t[0]);
	}
	public static int m1() {
		return 1;
	}
	public static int m2() {
		return 1;
	}
	public static int m3() {
		return 1;
	}
}
